# **4 TO - DO - Task**
Please complete all the problem listed below.

## **4.1 Exercise on Functions:**

### **Task - 1:**
Create a Python program that converts between different units of measurement.
*   The program should:
    1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
    2. Ask the user to input the value to be converted.
    3. Perform the conversion and display the result.
    4. Handle potential errors, such as invalid input or unsupported conversion types.
*   Requirements:
    1. **Functions:** Define at least one function to perform the conversion.
    2. **Error Handling:** Use try-except blocks to handle invalid input (e.g., non-numeric values).
    3. **User Input:** Prompt the user to select the conversion type and input the value.
    4. **Docstrings:** Include a docstring in your function to describe its purpose, parameters, and return value.
*   Conversion Options:
    1. **Length:**
        - Convert meters (m) to feet (ft).
        - Convert feet (ft) to meters (m).
    2. **Weight:**
        - Convert kilograms (kg) to pounds (lbs).
        - Convert pounds (lbs) to kilograms (kg).
    3. **Volume:**
        - Convert liters (L) to gallons (gal).
        - Convert gallons (gal) to liters (L).

In [ ]:
def convert_units(conversion_type, value):
  """
  Converts units between length, weight, and volume.

  Parameters:
    conversion_type (int): The selected conversion option.
    value (float): The numeric value to convert.

  Returns:
    float: The converted value.
  """

  # Length conversions
  if conversion_type == 1:          # meters to feet
    return value * 3.28084
  elif conversion_type == 2:        # feet to meters
    return value / 3.28084

  # Weight conversions
  elif conversion_type == 3:        # kilograms to pounds
    return value * 2.20462
  elif conversion_type == 4:        # pounds to kilograms
    return value / 2.20462

  # Volume conversions
  elif conversion_type == 5:        # liters to gallons
    return value * 0.264172
  elif conversion_type == 6:        # gallons to liters
    return value / 0.264172

  else:
    raise ValueError("Unsupported conversion type selected.")

try:
  print("Unit Conversion Program")
  print("Choose a conversion type:")
  print("1. Meters (m) to Feet (ft)")
  print("2. Feet (ft) to Meters (m)")
  print("3. Kilograms (kg) to Pounds (lbs)")
  print("4. Pounds (lbs) to Kilograms (kg)")
  print("5. Liters (l) to Gallons (gal)")
  print("6. Gallons (gal) to Liters (l)")

  choice = int(input("Enter your choice (1-6): "))
  value = float(input("Enter the value to convert: "))

  result = convert_units(choice, value)

  print("Converted value:", result)

except ValueError as e:
  print("Error:", e)

except Exception:
  print("Invalid input. Please enter numeric values only.")

Unit Conversion Program
Choose a conversion type:
1. Meters (m) to Feet (ft)
2. Feet (ft) to Meters (m)
3. Kilograms (kg) to Pounds (lbs)
4. Pounds (lbs) to Kilograms (kg)
5. Liters (l) to Gallons (gal)
6. Gallons (gal) to Liters (l)
Enter your choice (1-6): 1
Enter the value to convert: 10
Converted value: 32.8084


### **Task - 2:**
Create a Python program that performs various mathematical operations on a list of numbers.
*   The Program should:
    1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers).
    2. Ask the user to input a list of numbers (separated by spaces).
    3. Perform the selected operation and display the result.
    4. Handle potential errors, such as invalid input or empty lists.
*   **Requirements:**
    1. **Functions:** Define at least one function for each operation (sum, average, maximum, minimum).
    2. **Error Handling:** Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).
    3. **User Input:** Prompt the user to select the operation and input the list of numbers.
    4. **Docstrings:** Include a docstring in each function to describe its purpose, parameters, and return value.

In [ ]:
def calculate_sum(numbers):
  """
  Returns the sum of a list of numbers.

  Parameters:
    numbers (list of float): List of numeric values.

  Returns:
    float: Sum of the numbers.
  """
  total = 0
  for number in numbers:
    total += number
  return total

def calculate_average(numbers):
  """
  Returns the average of a list of numbers.

  Parameters:
    numbers (list of float): List of numeric values.

  Returns:
    float: Average of the numbers.
  """
  if len(numbers) == 0:
    raise ValueError("Cannot calculate average of an empty list.")
  return calculate_sum(numbers) / len(numbers)

def find_maximum(numbers):
  """
  Returns the maximum value in a list of numbers.

  Parameters:
    numbers (list of float): List of numeric values.

  Returns:
    float: Maximum value.
  """
  if len(numbers) == 0:
    raise ValueError("Cannot find maximum of an empty list.")

  maximum = numbers[0]
  for number in numbers:
    if number > maximum:
      maximum = number
  return maximum

def find_minimum(numbers):
  """
  Returns the minimum value in a list of numbers.

  Parameters:
    numbers (list of float): List of numeric values.

  Returns:
    float: Minimum value.
  """
  if len(numbers) == 0:
    raise ValueError("Cannot find minimum of an empty list.")

  minimum = numbers[0]
  for number in numbers:
    if number < minimum:
      minimum = number
  return minimum

try:
  print("Mathematical Operations Program")
  print("Choose an operation:")
  print("1. Sum")
  print("2. Average")
  print("3. Maximum")
  print("4. Minimum")

  choice = int(input("Enter your choice (1-4): "))

  user_input = input("Enter numbers separated by spaces: ")

  numbers = [float(x) for x in user_input.split()]

  if len(numbers) == 0:
    raise ValueError("The list cannot be empty.")

  if choice == 1:
    result = calculate_sum(numbers)
    print("Sum:", result)

  elif choice == 2:
    result = calculate_average(numbers)
    print("Average:", result)

  elif choice == 3:
    result = find_maximum(numbers)
    print("Maximum:", result)

  elif choice == 4:
    result = find_minimum(numbers)
    print("Minimum:", result)

  else:
    raise ValueError("Invalid operation selected.")

except ValueError as e:
  print("Error:", e)

except Exception:
  print("Invalid input. Please enter numbers correctly.")

Mathematical Operations Program
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 1
Enter numbers separated by spaces: 5 10 15
Sum: 30.0


## **4.2 Exercise on List Manipulation:**

### **1. Extract Every Other Element:**
Write a Python function that extracts every other element from a list, starting from the first element.
*   **Requirements:**
    *   Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.
    *   Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
  """
  Returns every other element from the list starting from the first element.

  Parameters:
    lst (list): The original list.

  Returns:
    list: A new list containing every other element.
  """
  return lst[::2]

numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)
print(result)

[1, 3, 5]


### **2. Slice a Sublist:**
Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.
*   **Requirements:**
    *   Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).
    *   Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
  """
  Returns a sublist from start index to end index (inclusive).

  Parameters:
    lst (list): The original list.
    start (int): Starting index of the sublist.
    end (int): Ending index of the sublist (inclusive).

  Returns:
    list: A sublist from start to end (inclusive).
  """
  return lst[start:end+1]

numbers = [1, 2, 3, 4, 5, 6]
sublist = get_sublist(numbers, 2, 4)
print(sublist)

[3, 4, 5]


### **3. Reverse a List Using Slicing:**
Write a Python function that reverses a list using slicing.
*   **Requirements:**
    *   Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.
    *   Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
  """
  Returns a reversed version of the input list using slicing.

  Parameters:
    lst (list): The original list.

  Returns:
    list: A new list with elements in reverse order.
  """
  return lst[::-1]

numbers = [1, 2, 3, 4, 5]
reversed_numbers = reverse_list(numbers)
print(reversed_numbers)

[5, 4, 3, 2, 1]


### **4. Remove the First and Last Elements:**
Write a Python function that removes the first and last elements of a list and returns the resulting sublist.
*   **Requirements:**
    *   Define a function remove first last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing.
    *   Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
  """
  Returns a sublist without the first and last elements.

  Parameters:
    lst (list): The original list.

  Returns:
    list: List without first and last elements.
  """
  return lst[1:-1]

numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)
print(result)

[2, 3, 4]


### **5. Get the First n Elements:**
Write a Python function that extracts the first n elements from a list.
*   **Requirements:**
    *   Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.
    *   Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
  """
  Returns the first n elements of the list.

  Parameters:
    lst (list): The original list.
    n (int): Number of elements to extract.

  Returns:
    list: A new list containing the first n elements.
  """
  return lst[:n]

numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)
print(result)

[1, 2, 3]


### **6. Extract Elements from the End:**
Write a Python function that extracts the last n elements of a list using slicing.
*   **Requirements:**
    *   Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.
    *   Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
  """
  Returns the last n elements of the list.

  Parameters:
    lst (list): The original list.
    n (int): Number of elements to extract from the end.

  Returns:
    list: A new list containing the last n elements.
  """
  return lst[-n:]

numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)
print(result)

[4, 5]


### **7. Extract Elements in Reverse Order:**
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.
*   **Requirements:**
    *   Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.
    *   Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
  """
  Returns every second element starting from the second-to-last element, moving backward.

  Parameters:
    lst (list): The original list.

  Returns:
    list: A new list with elements in reverse order, skipping one element each time.
  """
  return lst[-2::-2]

numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)
print(result)

[5, 3, 1]


## **4.3 Exercise on Nested List:**

### **1. Flatten a Nested List:**
Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.
*   **Requirements:**
    *   Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.
    *   Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
  """
  Flattens a nested list into a single list.

  Parameters:
    lst (list): A nested list.

  Returns:
    list: A flattened list.
  """
  flat_list = []
  for sublist in lst:
    for item in sublist:
      flat_list.append(item)
  return flat_list

numbers = [[1, 2], [3, 4], [5]]
result = flatten(numbers)
print(result)

[1, 2, 3, 4, 5]


### **2. Accessing Nested List Elements:**
Write a Python function that extracts a specific element from a nested list given its indices.
*   **Requirements:**
    *   Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.
    *   Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
  """
  Returns a specific element from a nested list based on a list of indices.

  Parameters:
    lst (list): A nested list.
    indices (list): A list of indices showing the path.

  Returns:
    element at the specified nested position.
  """
  element = lst
  for index in indices:
    element = element[index]
  return element

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
result = access_nested_element(lst, [1, 2])
print(result)

6


### **3. Sum of All Elements in a Nested List:**
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
*   **Requirements:**
    *   Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.
    *   Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
  """
  Returns the sum of all numbers in a nested list (any depth).

  Parameters:
    lst (list): A nested list containing numbers.

  Returns:
    int/float: Sum of all elements.
  """
  total = 0
  for item in lst:
    if isinstance(item, list):
      total += sum_nested(item)
    else:
      total += item
  return total

numbers = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(numbers)
print(result)

21


### **4. Remove Specific Element from a Nested List:**
Write a Python function that removes all occurrences of a specific element from a nested list.
*   **Requirements:**
    *   Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.
    *   Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
  """
  Removes all occurrences of elem from a nested list.

  Parameters:
    lst (list): A nested list.
    elem: Element to remove.

  Returns:
    list: Modified list with elem removed.
  """
  new_list = []

  for item in lst:
    if isinstance(item, list):
      new_list.append(remove_element(item, elem))
    else:
      if item != elem:
        new_list.append(item)

  return new_list

lst = [[1, 2], [3, 2], [4, 5]]
result = remove_element(lst, 2)
print(result)

[[1], [3], [4, 5]]


### **5. Find the Maximum Element in a Nested List:**
Write a Python function that finds the maximum element in a nested list (regardless of depth).
*   **Requirements:**
    *   Define a function find max(lst) that takes a nested list lst and returns the maximum element.
    *   Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
  """
  Finds the maximum element in a nested list (any depth).

  Parameters:
    lst (list): A nested list containing numbers.

  Returns:
    int/float: Maximum element in the list.
  """
  maximum = None

  for item in lst:
    if isinstance(item, list):
      value = find_max(item)
    else:
      value = item

    if maximum is None or value > maximum:
        maximum = value

  return maximum

numbers = [[1, 2], [3, [4, 5]], 6]
result = find_max(numbers)
print(result)

6


### **6. Count Occurrences of an Element in a Nested List:**
Write a Python function that counts how many times a specific element appears in a nested list.
*   **Requirements:**
    *   Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.
    *   Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.

In [ ]:
def count_occurrences(lst, elem):
  """
  Counts how many times elem appears in a nested list.

  Parameters:
    lst (list): A nested list.
    elem: Element to count.

  Returns:
    int: Number of occurrences of elem.
  """
  count = 0

  for item in lst:
    if isinstance(item, list):
      count += count_occurrences(item, elem)
    else:
      if item == elem:
        count += 1

  return count

lst = [[1, 2], [2, 3], [2, 4]]
result = count_occurrences(lst, 2)
print(result)

3


### **7. Flatten a List of Lists of Lists:**
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
*   **Requirements:**
    *   Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.
    *   Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
  """
  Flattens a deeply nested list into a single list.

  Parameters:
    lst (list): A deeply nested list.

  Returns:
    list: A completely flattened list.
  """
  flat_list = []

  for item in lst:
    if isinstance(item, list):
      flat_list.extend(deep_flatten(item))
    else:
      flat_list.append(item)

  return flat_list

lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(lst)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


### **8. Nested List Average:**
Write a Python function that calculates the average of all elements in a nested list.
*   **Requirements:**
    *   Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.
    *   Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
  """
  Calculates the average of all numbers in a nested list.

  Parameters:
    lst (list): A nested list containing numbers.

  Returns:
    float: Average of all elements.
  """

  def helper(sublist):
    total = 0
    count = 0

    for item in sublist:
      if isinstance(item, list):
        sub_total, sub_count = helper(item)
        total += sub_total
        count += sub_count
      else:
        total += item
        count += 1

    return total, count

  total_sum, total_count = helper(lst)
  return total_sum / total_count

lst = [[1, 2], [3, 4], [5, 6]]
result = average_nested(lst)
print(result)

3.5


# **10 To - Do - NumPy**
Please complete all the problems listed below:

## **10.1 Basic Vector and Matrix Operation with Numpy.**

### **Problem - 1: Array Creation:**
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2,2))
print("1. Empty array (2x2):\n", empty_array, "\n")

# 2. Initialize an all-one array with size 4X2
ones_array = np.ones((4,2))
print("2. All-one array (4x2):\n", ones_array, "\n")

# 3. Return a new array of given shape and type, filled with fill value
# Example: shape = (3,3), type = int, fill value = 7
filled_array = np.full((3,3), 7, dtype=int)
print("3. Array filled with 7:\n", filled_array, "\n")

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[5,6],[7,8]])
zeros_like_array = np.zeros_like(given_array)
print("4. Zeros like given array:\n", zeros_like_array, "\n")

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("5. Ones like given array:\n", ones_like_array, "\n")

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("6. Numpy array from list:\n", array_from_list)

1. Empty array (2x2):
 [[4.48673832e-315 0.00000000e+000]
 [6.92179552e-310 6.92179552e-310]] 

2. All-one array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

3. Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]] 

4. Zeros like given array:
 [[0 0]
 [0 0]] 

5. Ones like given array:
 [[1 1]
 [1 1]] 

6. Numpy array from list:
 [1 2 3 4]


### **Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("1. Array from 10 to 49:\n", arr1, "\n")

# 2. Create a 3X3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3,3)
print("2. 3x3 matrix from 0 to 8:\n", arr2, "\n")

# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("3. 3x3 Identity matrix:\n", identity_matrix, "\n")

# 4. Create a random array of size 30 and find the mean
rand_array = np.random.random(30)
mean_value = rand_array.mean()
print("4. Random array (size 30):\n", rand_array)
print("   Mean of array:", mean_value, "\n")

# 5. Create a 10X10 array with random values and find min & max
rand_matrix = np.random.random((10,10))
min_val = rand_matrix.min()
max_val = rand_matrix.max()
print("5. 10x10 random array:\n", rand_matrix)
print("   Min:", min_val, "Max:", max_val, "\n")

# 6. Create zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Indexing starts from 0
print("6. Zero array with 5th element 1:\n", zero_array, "\n")

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print("7. Reversed array:\n", reversed_arr, "\n")

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5,5))
border_array[1:-1, 1:-1] = 0
print("8. 2D array with 1 on border and 0 inside:\n", border_array, "\n")

# 9. Create 8X8 matrix with checkerboard pattern
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("9. 8x8 Checkerboard pattern:\n", checkerboard)

1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

2. 3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

3. 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

4. Random array (size 30):
 [6.01759533e-01 1.05902071e-01 3.62664899e-01 4.66354603e-01
 2.03659681e-01 7.89390178e-01 8.18753663e-02 7.48873741e-01
 2.32940141e-01 3.59738281e-02 9.34331403e-01 5.56795772e-01
 5.89767321e-01 1.76920384e-01 3.04238677e-01 6.93343883e-01
 8.24577476e-01 2.14379745e-01 2.98601030e-01 6.22451987e-01
 9.13926923e-04 3.11737534e-01 9.91781871e-01 7.95881592e-01
 3.77798486e-01 3.65670328e-01 1.61653354e-01 5.65286459e-01
 7.93355941e-01 8.78159816e-01]
   Mean of array: 0.46956803426344534 

5. 10x10 random array:
 [[0.16476023 0.78744097 0.61527546 0.9421254  0.84164064 0.50578734
  0.03879302 0.12535023 0.4117257  0.89501269]
 [0.13148547 0.45588171 0.65129417 0.00880382 0.95836955 0.245

### **Problem - 3: Array Operations:**
For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two arrays
add_xy = x + y
print("1. x + y:\n", add_xy, "\n")

# 2. Subtract the two arrays
sub_xy = x - y
print("2. x - y:\n", sub_xy, "\n")

# 3. Multiply the array with any integer (let's choose 3)
mul_x = x * 3
print("3. x * 3:\n", mul_x, "\n")

# 4. Find the square of each element
square_x = x ** 2
print("4. Square of each element in x:\n", square_x, "\n")

# 5. Dot products
dot_vw = np.dot(v, w)
print("5a. Dot product v.w:", dot_vw)

# Dot product x.v → Since v is 1D of length 2, it's compatible
dot_xv = np.dot(x, v)
print("5b. Dot product x.v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("5c. Dot product x.y:\n", dot_xy, "\n")

# 6. Concatenate
concat_xy_row = np.concatenate((x, y), axis=0)  # along row (vertically)
concat_vw_col = np.vstack((v, w)).T  # to concatenate as columns
print("6a. Concatenate x and y along row:\n", concat_xy_row)
print("6b. Concatenate v and w along column:\n", concat_vw_col, "\n")

# 7. Concatenate x and v → Will give error
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)
print("7. Attempt to concatenate x and v error:\n", concat_xv_error)
print("\nExplanation: x is a 2x2 array, v is 1D array of length 2. \
Concatenation along axis 0 requires arrays to have the same number of columns, \
but here x has 2 columns and v is 1D (shape (2,)), so numpy throws an error.")

1. x + y:
 [[ 6  8]
 [10 13]] 

2. x - y:
 [[-4 -4]
 [-4 -3]] 

3. x * 3:
 [[ 3  6]
 [ 9 15]] 

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]] 

5a. Dot product v.w: 219
5b. Dot product x.v:
 [29 77]
5c. Dot product x.y:
 [[19 22]
 [50 58]] 

6a. Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Concatenate v and w along column:
 [[ 9 11]
 [10 12]] 

7. Attempt to concatenate x and v error:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation: x is a 2x2 array, v is 1D array of length 2. Concatenation along axis 0 requires arrays to have the same number of columns, but here x has 2 columns and v is 1D (shape (2,)), so numpy throws an error.


### **Problem - 4: Matrix Operations:**
*   For the following arrays:

    A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
    
    Prove following with Numpy:
    1. Prove A.A−1 = I.
    2. Prove AB ̸= BA.
    3. Prove (AB)T = BT AT.
*   Solve the following system of Linear equation using Inverse Methods.
    
                                2x−3y + z =−1
                                
                                x−y + 2z =−3
                                
                                3x + y−z = 9
    {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX= B}
*   Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [ ]:
import numpy as np

# Given matrices
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("1. A * A^-1:\n", identity_check)
print("   Should approximate Identity matrix\n")

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("2. AB:\n", AB)
print("   BA:\n", BA)
print("   AB != BA is", not np.array_equal(AB, BA), "\n")

# 3. Prove (AB)^T = B^T A^T
AB_transpose = np.dot(A,B).T
BT_AT = np.dot(B.T, A.T)
print("3. (AB)^T:\n", AB_transpose)
print("   B^T A^T:\n", BT_AT)
print("   Equality check:", np.array_equal(AB_transpose, BT_AT), "\n")

# Solve the system of linear equations using inverse method
# Equations:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# Represent in matrix form AX = B
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve using inverse
A_eq_inv = np.linalg.inv(A_eq)
X = np.dot(A_eq_inv, B_eq)
print("Solution using inverse method:\n", X)

# Optional: Verify solution by AX = B
B_check = np.dot(A_eq, X)
print("Verify AX = B:\n", B_check)

1. A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
   Should approximate Identity matrix

2. AB:
 [[23 13]
 [51 29]]
   BA:
 [[36 44]
 [13 16]]
   AB != BA is True 

3. (AB)^T:
 [[23 51]
 [13 29]]
   B^T A^T:
 [[23 51]
 [13 29]]
   Equality check: True 

Solution using inverse method:
 [ 2.  1. -2.]
Verify AX = B:
 [-1. -3.  9.]


## **10.2 Experiment: How Fast is Numpy?**
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

### **1. Element-wise Addition:**
*   Using **Python Lists**, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
*   Using **Numpy Arrays**, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

# 1. Using Python Lists
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
python_time = end_time - start_time
print("Time taken for element-wise addition using Python lists:", python_time, "seconds\n")

# 2. Using NumPy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
array_sum = arr1 + arr2
end_time = time.time()
numpy_time = end_time - start_time
print("Time taken for element-wise addition using NumPy arrays:", numpy_time, "seconds\n")

# Comparison
speedup = python_time / numpy_time
print(f"NumPy is approximately {speedup:.2f} times faster than Python lists for element-wise addition.")

Time taken for element-wise addition using Python lists: 0.11049842834472656 seconds

Time taken for element-wise addition using NumPy arrays: 0.0041484832763671875 seconds

NumPy is approximately 26.64 times faster than Python lists for element-wise addition.


### **2. Element-wise Multiplication**
*   Using **Python Lists**, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
*   Using **Numpy Arrays**, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

# Array size
size = 1_000_000

# 1. Using Python Lists
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
python_time = end_time - start_time
print("Time taken for element-wise multiplication using Python lists:", python_time, "seconds\n")

# 2. Using NumPy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
array_product = arr1 * arr2
end_time = time.time()
numpy_time = end_time - start_time
print("Time taken for element-wise multiplication using NumPy arrays:", numpy_time, "seconds\n")

# Comparison
speedup = python_time / numpy_time
print(f"NumPy is approximately {speedup:.2f} times faster than Python lists for element-wise multiplication.")

Time taken for element-wise multiplication using Python lists: 0.1960129737854004 seconds

Time taken for element-wise multiplication using NumPy arrays: 0.0038805007934570312 seconds

NumPy is approximately 50.51 times faster than Python lists for element-wise multiplication.


### **3. Dot Product**
*   Using **Python Lists**, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
*   Using **Numpy Arrays**, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

# Array size
size = 1_000_000

# 1. Using Python Lists
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
python_time = end_time - start_time
print("Time taken for dot product using Python lists:", python_time, "seconds\n")

# 2. Using NumPy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
dot_array = np.dot(arr1, arr2)
end_time = time.time()
numpy_time = end_time - start_time
print("Time taken for dot product using NumPy arrays:", numpy_time, "seconds\n")

# Comparison
speedup = python_time / numpy_time
print(f"NumPy is approximately {speedup:.2f} times faster than Python lists for dot product.")

Time taken for dot product using Python lists: 0.10861968994140625 seconds

Time taken for dot product using NumPy arrays: 0.0016186237335205078 seconds

NumPy is approximately 67.11 times faster than Python lists for dot product.


### **4. Matrix Multiplication**
*   Using **Python lists**, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
*   Using **NumPy arrays**, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.


In [11]:
import numpy as np
import time

# Matrix size
size = 1000

# 1. Using Python Lists
# Create two 1000x1000 matrices filled with 1s
matrix1 = [[1 for _ in range(size)] for _ in range(size)]
matrix2 = [[1 for _ in range(size)] for _ in range(size)]

start_time = time.time()

# Initialize result matrix
result = [[0 for _ in range(size)] for _ in range(size)]

# Perform matrix multiplication (triple nested loop)
for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += matrix1[i][k] * matrix2[k][j]

end_time = time.time()
python_time = end_time - start_time
print("Time taken for matrix multiplication using Python lists:", python_time, "seconds\n")

# 2. Using NumPy Arrays
arr1 = np.ones((size, size))
arr2 = np.ones((size, size))

start_time = time.time()
result_np = np.dot(arr1, arr2)  # or arr1 @ arr2
end_time = time.time()
numpy_time = end_time - start_time
print("Time taken for matrix multiplication using NumPy arrays:", numpy_time, "seconds\n")

# Comparison
speedup = python_time / numpy_time
print(f"NumPy is approximately {speedup:.2f} times faster than Python lists for matrix multiplication.")

Time taken for matrix multiplication using Python lists: 306.84714579582214 seconds

Time taken for matrix multiplication using NumPy arrays: 0.10473299026489258 seconds

NumPy is approximately 2929.80 times faster than Python lists for matrix multiplication.
